name: Socket Service Cloud Run Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./todobackend
          file: ./todobackend/Dockerfile
          push: true
          tags: gcr.io/todogoals-ea6d4/todobackend:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/todogoals-ea6d4/todobackend:latest
          service: todobackend
          region: asia-south1
          no_traffic: true

      - name: Verify new deployment
        run: | # Optionally add your health check commands here
          echo "Check the new deployment health"

      - name: Migrate traffic
        run: |
          gcloud run services update-traffic todobackend --to-latest --region asia-south1 --platform managed
